import SwiftUI
import UIKit

// MARK: - Design System Colors
// Matches web app color scheme for consistency across platforms
//
// | UI Element           | Color       | Hex     |
// |----------------------|-------------|---------|
// | Primary CTA buttons  | Coral       | #FF914D |
// | Links & focus rings  | Teal        | #4DB8C4 |
// | Tab bar / nav tint   | Teal        | #4DB8C4 |
// | Badges & tags        | Coral       | #FF914D |
// | Highlights / accents | Golden      | #FFEB2E |
// | Delete / error       | Destructive | #F75757 |
// | Screen background    | Cream/Dark  | #F9F5F0 / #1F1B2E |
// | Section backgrounds  | Peach       | #FDEDD8 |
// | Secondary text       | Gray        | #737373 |
// | Success states       | Sage        | #A6C4B8 |
// | Upgrade banners      | Golden Light| #FFFF80 |

// Convenience aliases for cleaner code
// Note: Most colors are auto-generated by Xcode from Assets catalog.
// Only add extensions here for colors that need custom naming or aren't in Assets.
extension Color {
    // Primary brand color (Coral) - alias for BrandColor asset
    static var brandOrange: Color { Color("BrandColor") }
}

// The following colors are auto-generated from Assets catalog:
// - Color.tealAccent (#4DB8C4)
// - Color.goldenAccent (#FFEB2E)
// - Color.goldenLight (#FFFF80)
// - Color.errorColor (#F75757)
// - Color.successColor (#A6C4B8)
// - Color.backgroundColor (#F9F5F0 / #1F1B2E)
// - Color.peachBackground (#FDEDD8)
// - Color.cardBackground
// - Color.mutedText (#737373)

// MARK: - Button Styles
struct BrandButtonStyle: ButtonStyle {
    var isDisabled: Bool = false

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .frame(maxWidth: .infinity)
            .padding(.vertical, 16)
            .background(
                isDisabled
                    ? Color.brandOrange.opacity(0.5)
                    : (configuration.isPressed ? Color.brandOrange.opacity(0.8) : Color.brandOrange)
            )
            .foregroundColor(.white)
            .font(.system(size: 16, weight: .bold))
            .cornerRadius(16)
            .shadow(color: Color.brandOrange.opacity(0.3), radius: 8, x: 0, y: 4)
    }
}

struct SecondaryButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .frame(maxWidth: .infinity)
            .padding(.vertical, 14)
            .background(
                configuration.isPressed
                    ? Color(UIColor.systemGray5)
                    : Color(UIColor.systemBackground)
            )
            .foregroundColor(.primary)
            .font(.system(size: 15, weight: .semibold))
            .cornerRadius(14)
            .overlay(
                RoundedRectangle(cornerRadius: 14)
                    .stroke(Color(UIColor.systemGray4), lineWidth: 1)
            )
    }
}

// MARK: - Text Field Styles
struct BrandTextFieldStyle: TextFieldStyle {
    var icon: String? = nil

    func _body(configuration: TextField<Self._Label>) -> some View {
        HStack(spacing: 12) {
            if let icon = icon {
                Image(systemName: icon)
                    .foregroundColor(.mutedText)
                    .frame(width: 20)
            }
            configuration
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 14)
        .background(Color(UIColor.systemBackground))
        .cornerRadius(14)
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(Color(UIColor.systemGray4).opacity(0.5), lineWidth: 1)
        )
    }
}

// MARK: - View Modifiers
struct PeachHeaderModifier: ViewModifier {
    func body(content: Content) -> some View {
        content
            .background(Color.peachBackground)
    }
}

extension View {
    func peachHeader() -> some View {
        modifier(PeachHeaderModifier())
    }
}
